let s = 'KCIBALHMDDEJMBLOOFINNOGCPCHLHBAONHAKKIFAFGJGLPMAAMAIOIEOOMIPIGBCFMGBAACCJAHAEJOPFOGGKIIMANEIBFABMFCNDPNFHDGCBBLOAKAKHFINACODKDGKNCAIKIHKCFKCKKBHIMEADPEAPBADOFHEHAHAHFACNLHCMIHHHOFCMENKDHIGNNLBAAJJMEJFMHMMCHEMDADIMEAKPEIPPGACAFAHONMEECONLMGJAKAPDPIHNIFCBCHLFMNCMECDMHHGHIOFOAIHNAAAJCJHNCHFAMJCFGEMCMCHHMCNAHJOOIFKGHIBLDPEOAEBNGAALAAHEOKJKFINIHGDBDHJOCDACHHEAAHKFHIGIKHPMMCLPCEMCOCKNEMIOAOOMEAKCACDHADNFMGNNACHAHFCMKLGNHANKIFDFFPHLABMHAFLOIAMGDCLFDEKHAHBMEACHGHPPGCNHOHBMENCMCHMIGDMFEGEOIBOBKILCPMPFAHCEBAJJOKICLDFEAJFBMLAAPAEGBDJDKPCKKIMNNEKOPFLPAOPMEAJPHAPKJDLJAKNJAANFOHKEPJOAOAOAAIFIDAPEFJFKHIPNAFONPNNGCNHAHAHKIFFOCHNALOBNCOCNAHKPHILCCCIFNGADHANEAAJDMPBKKKNAAIKENIMDCFFAKJBCHIAHJJKACKGAIAPKIEHIAHGICBPDKHKCHIFCPMPMKGKMDEIEOPAAJJKEBLMMKCGAJIFCPGOEGLPAEADOIJNIHALFNHENFAOAAGNEHOMAABOAMAMBNECJDHGICPHNOACEBNADCAKIOLHOCONONHDKCDOPPGNACAMOIKAFNJOBCGDNCOCNAHKBJIEPABOFNGLDHAKHEIFJMFKHAHFHFAKCJIMAFKCKMIPAACFDDAJOPDFANJAONAOBEIGIFBLOAIEJPAADFAJNAKFKCIBHHHOOMIHMIEMKHIAFAFOKJNMDAFPHFFNMCGONDOAILBGOMIOAACMOMCBCFENDMHAFGEACIABNADEFCGMNAHOJDIHEIHFMDEHDPPCBPHHANIBMICGOIENCKOLECIBKDIEKIDAIFAEEGMJKKIDHFICHCHKCFPHMBECOONAHMJFJECNEEJBOIBACPAFMBAEENOFDHAOIBICIEBHAEAGAJJDAGHMLCHMNCAIMEKAMFJCHFJDDFHIOIAKIMILFDMCOAINHFAADAAEPHJKDKEDKIKMAJELOJNDCKHHNOINHLAIKDDHDMPAKKEFGFNIBCPNDKDMAJIKNOIOIBBPKKKCAAIKPGIICBDEOONBCHOKDBIKOOLOANJDHFAOKEIPAJEHANAKEBGHICLDHHGFFMGFAJCOBCINBOOKFOGJFGOFFAMBCFLEBOPIAAEDADLGJFACMKCFAAIOBGOLOPIHMMCFDEEFFLGIDBJHEDBLHFPDDCPHDHEKFACCOIACLDDFCMCHFFBJ';
let arr = [];
    let a = 32;
    for (let i = 0; i < s.length; i++) {
        if (a === 32) {
            arr.push(s.slice(i, i + 32));
            a = 0;
        }
        a += 1;
    }

let shifts = {
    0 : [2, 0],
    1 : [6, 1],
    2 : [5, 4],
    3 : [10, 7],
    4 : [18, 16],
    5 : [21, 20],
    6 : [22, 17],
    7 : [26, 23],
};

let pairs = {};
for (let i = 0; i < shifts.length; i++) {
  for (let el of arr) {
    pairs[`${el[shifts[i][0]]}${el[shifts[i][1]]}`] = 0;
  }
}

for (let i = 0; i < shifts.length; i++) {
  for (let el of arr) {
    pairs[`${el[shifts[i][0]]}${el[shifts[i][1]]}`] += 1;
  }
}

let total = 0;
for (let pair in pairs) {
  total += pairs[pair];
}
let result = [];
for (let pair in pairs) {
  result.push(`${pair} = ${(pairs[pair] / total * 100).toFixed(2)}%`);
}
console.log(result);
